### ISSUE TITLE
Ability to embed the map with events on external sites

### ISSUE THREAD

**Issue by bzg** [codeeu/codeeu.github.io#126]
I've found this map in the code:

> ... iframe src="http://mapsengine.google.com/map/embed?mid=zlK9lh_7YlUI.kDtxSLI7E0Fs" width="100%" height="480"

Apparently, it's not the correct map.

What map can I use with iframe in our codeweekfrance.org website?

Thanks,

**Comment by joseihf** [comment]
I´m working on it. 

In a few days I hope to have it ready

**Comment by bzg** [comment]
Great, thanks.

**Comment by mitio** [comment]
@bzg is this the issue where you're proposing to have an embeddable map of Code Week events?

**Comment by mitio** [comment]
@joseihf Bastien had the great idea of allowing people to embed the events map. For this, we would probably need just a page with no layout and only the map, in full width and height. In addition, we could add a few filters to be applied via query parameters (e.g. to show or not past events, to filter by country, where to center the map, how much to zoom and things like this). Filtering is lower priority, though. First we need to have an URL to allow embedding what we show by default on the homepage.

@bzg Correct me if I'm missing something.

**Comment by mitio** [comment]
Actually, this should be implemented in the https://github.com/codeeu/coding-events repo.

**Comment by joseihf** [comment]
I have do it: https://github.com/codeeu/coding-events/commit/7ac3648d82fcfbad28386b562a32891a1b85b471 ;-)

**Comment by mitio** [comment]
@joseihf I think you mean http://events.codeweek.eu/map/

The map there is not full height. Can we fix that?

**Comment by mitio** [comment]
It would be great if we prepare somewhere an example code for embedding.

**Comment by bzg** [comment]
Thanks @joseihf for providing this, very handy!

> iframe width="900" height="450" src="http://events.codeweek.eu/map/"

looks fine here, I will update http://www.codeweekfrance.org with this soon.

**Comment by mitio** [comment]
I'm declaring this resoved for now, esp. when we also have an API for the events at http://events.codeweek.eu/api/event/list/.
