### ISSUE TITLE
Where is the "Events Guide" page in the Repo? 

### ISSUE THREAD

**Issue by tyrower** [codeeu/codeeu.github.io#151]
I'd like to help update some of the details on the pages of the website. 

For instance adding recent materials here : 
![image](https://cloud.githubusercontent.com/assets/6247604/16068723/8ed0abda-32c8-11e6-8abb-0eae9b542621.png)

Where is the http://events.codeweek.eu/guide/ file in the GH repo so that we could edit and submit a PR please ?

**Comment by mitio** [comment]
@tyrower Thanks for your help! 🙇 

The page you're looking for is located in another repo: https://github.com/codeeu/coding-events/blob/master/web/templates/pages/guide.html

Let us know if you need anything else.

**Comment by tyrower** [comment]
TY



[image: --]

Alan McCullagh
[image: https://]about.me/alan.mccullagh
<https://about.me/alan.mccullagh?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
